[project]
name = "imox-analytics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Eduardo Augusto Rabelo Socca", email = "eduardo_socca@yahoo.com.br" }
]
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.4.0",
    "nbformat>=5.11.1",
    "pandas>=3.0.6",
    "plotly>=7.1.0",
    "python-dotenv>=1.2.4",
    "requests>=2.34.2",
]

[project.scripts]
imox-analytics = "imox_analytics:main"

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"
